### ISSUE TITLE
Extended View mispositioned

### ISSUE THREAD

**Issue by MarceloPrado** [tristanhimmelman/HidingNavigationBar#1]
Whenever I create an extended view on table view controller, it appears on the middle of the screen. Any suggestion? I saw that sample code uses a ui table view, and not controller. It its possible to add extended view to ui table view controller?
Thanks

**Comment by tristanhimmelman** [comment]
Hi there, sorry for the slow reply. Unfortunately this library doesn't support UITableViewControllers.
