### ISSUE TITLE
Usage is too flexible, and it's not same with example Demo.

### ISSUE THREAD

**Issue by Seaofbbs** [tristanhimmelman/HidingNavigationBar#18]
install with pod ~2.1, but it can't recorecognized the type "HidingNavgationBarManager"
![2016-01-07 4 29 39](https://cloud.githubusercontent.com/assets/13342724/12165804/f31f4fa0-b55b-11e5-88f6-556c957e3f79.png)

**Comment by Seaofbbs** [comment]
Problem solved!
 I Removing HidingNavigationBar in cocoaPods. Change to drag the .swift files.
Everything is ok now.

**Comment by Seaofbbs** [comment]
I used to import HidingNavigationBar  for module. But Xcode can't recognized it name of module.
even in XXX-bridge.h

**Comment by tristanhimmelman** [comment]
Great, glad the issue is resolved :+1:
