### ISSUE TITLE
HidingNavigationBar Integration Issue

### ISSUE THREAD

**Issue by LuaiKalkatawi** [tristanhimmelman/HidingNavigationBar#29]
I have added the the library through CocoaPods and after that I have tried to  add the variable of HidingNavigationBarManager but I'm getting this issue 

> Use of undeclalead type 'HidingNavigationBarManager'

Should I import something else?

Thanks.

**Comment by tristanhimmelman** [comment]
Have you included `import HidingNavigationBar` at the top of your class?

**Comment by LuaiKalkatawi** [comment]
Yes I have imported it but it couldn't work until I removed it from the pod and install it again from the pod and it started to work. Anyway it is working. Thanks.
