### ISSUE TITLE
Hiding status bar expands navigation bar

### ISSUE THREAD

**Issue by VrasidasP** [tristanhimmelman/HidingNavigationBar#3]
How to reproduce in the demo project:
Add this to HidingNavViewController.swift:

func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
        UIApplication.sharedApplication() .setStatusBarHidden(true, withAnimation: UIStatusBarAnimation.Slide)
    }

and then go to Hiding Nav Bar, scroll down a bit so that the bar collapses, and tap on a row.
The bar will then expand but without resetting the subviews' alpha values.

Is this a quick fix? I'm not very experienced in Swift.
Thank you!

**Comment by tristanhimmelman** [comment]
A quick fix for this issue is to call one of these two functions after hiding the status bar

```
hidingNavBarManager?.contract()
```

or 

```
hidingNavBarManager?.expand()
```

I'll look into this further to see if I can find a better fix.

Hope this helps

**Comment by VrasidasP** [comment]
Ok, this works for now.
Thanks! :)
