### ISSUE TITLE
Hiding NavigationBar leaves a blackbar

### ISSUE THREAD

**Issue by Brotakuu** [tristanhimmelman/HidingNavigationBar#4]
There's a black bar that's left after NavigationBar hides. It blocks the tableView.

**Comment by sumesh1993** [comment]
yes. it leaves a black bar if the navigation bars translucent property is set to false
pls suggest a fix

**Comment by tristanhimmelman** [comment]
HidingNavigationBar only supports translucent navigation bar at the moment
