### ISSUE TITLE
Extra top margin

### ISSUE THREAD

**Issue by black-lotus** [tristanhimmelman/HidingNavigationBar#45]
![simulator screen shot aug 4 2016 12 04 11 pm](https://cloud.githubusercontent.com/assets/3261560/17390968/1fadbc20-5a3c-11e6-9b4f-fee59437c6d9.jpg)

i use storyboard :)
hope will fixed

Thanks

**Comment by suhitp** [comment]
@black-lotus By default
storyboard add tableview top constraint to "Top Layout Guide.Bottom", you need to change the tableview.top constraint to "View.Top". Refer the image
[
<img width="930" alt="screen shot 2016-09-24 at 7 18 11 pm" src="https://cloud.githubusercontent.com/assets/6196402/18808895/3746a496-828c-11e6-830a-d2ee85e599b6.png">
](url)

**Comment by black-lotus** [comment]
Nice

Thank you :)
