### ISSUE TITLE
issue 'isnan' is unavailable: use the isNaN property. in Swift 3

### ISSUE THREAD

**Issue by X901** [tristanhimmelman/HidingNavigationBar#48]
Hi , I have this issue after I convert my project to Swift 3

**Comment by X901** [comment]
I fix the error , after convert the library to Swift 3
you will notice the problem in this line
if isnan(previousYOffset) == false 
and the error " 'isnan' is unavailable: use the isNaN property. "

change this line from " if isnan(previousYOffset) == false "  to
" if previousYOffset.isNaN == false "

After that the library will work in Swift 3

**Comment by tristanhimmelman** [comment]
I have just updated the library with swift3 support. Please use v1.0.0
