### ISSUE TITLE
Section header view below navigation bar after on appearance

### ISSUE THREAD

**Issue by alpennec** [tristanhimmelman/HidingNavigationBar#6]
Hi,

I have a UITableView in a UINavigationController. My tableView contains sections headers.

When I click on the cell, I push another viewController. I call 

```
hidingNavBarManager?.viewWillDisappear(animated)
```

When the user goes back, the section header is hidden below the navigationBar, as if the tableView had not scrolled. Any idea how to scroll the tableview so the header section is not below the navigation bar on appearance?

Thanks

**Comment by tristanhimmelman** [comment]
This should be resolved now, thanks to the PR above
